version: "3.9"
services:
  battleships-db:
    container_name: battleships-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daw_g03
    ports:
      - "5432:5432"

  battleships-service-1:
    container_name: battleships-service-1
    depends_on:
      - battleships-db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://battleships-db/daw_g03
    expose:
      - "80"

  battleships-service-2:
    container_name: battleships-service-2
    depends_on:
      - battleships-service-1
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://battleships-db/daw_g03
    expose:
      - "80"

  battleships-nginx:
    container_name: battleships-nginx
    depends_on:
      - battleships-service-1
      - battleships-service-2
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
