version: "3.9"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=daw_g03
    ports:
      - "5432:5432"

  battleships-service-1:
    container_name: battleships-service-1
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    image: battleships-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/daw_g03
    ports:
      - "8081:8080"

  battleships-service-2:
    container_name: battleships-service-2
    depends_on:
      - db
      - battleships-service-1
    image: battleships-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/daw_g03
    ports:
      - "8082:8080"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./dockerfiles/nginx:/etc/nginx
    depends_on:
      - battleships-service-1
      - battleships-service-2