FROM postgres

ENV PORT=5432

USER postgres
WORKDIR /app

COPY code/sql/createSchema.sql /docker-entrypoint-initdb.d/1_create.sql

COPY --chown=postgres:postgres ./dockerfiles/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE $PORT
