server:
  secret: 885650279fb7ff19a771c556f0c6ffad7092a26948db8df42cd8009745ebb545
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost/daw_g03
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
